from mongoengine import *

class WellnessCenterRegistration(Document):
	firstName = StringField()
	lastName = StringField()
	emailId = StringField()
	phoneNumber = StringField()
	password = StringField()
	profilePic = StringField()
	hsRefLink = StringField()
	createdOn = DateTimeField()
	status = IntField()

class StudentDailySickRegistration(Document):
	studentName = StringField()
	className = StringField()
	rollNumber = StringField()
	diseaseName = StringField()
	date = StringField()
	time = StringField()
	day = StringField()
	medicineIssued = StringField()
	permissionLetter = StringField()
	hsRefLink = ReferenceField('WellnessCenterRegistration')
	hsId = ReferenceField('WellnessCenterRegistration')
	hsName = ReferenceField('WellnessCenterRegistration')
	studentRefLink = StringField()
	createdOn = DateTimeField()
	status = IntField()


class StudentSickDiet(Document):
	studentName = StringField()
	className = StringField()
	rollNumber = StringField()
	studentRefLink = StringField()
	studentId = ReferenceField('StudentDailySickRegistration')
	hsId = ReferenceField('WellnessCenterRegistration')
	# hsRefLink = ReferenceField('WellnessCenterRegistration')
	medicineIssued = StringField()
	diseaseName = StringField()
	foodItem = StringField()
	foodQuantity = StringField()
	numberOfTimes = StringField()
	sickDietStudentRefLink = StringField()
	createdOn = DateTimeField()
	sickDietStatus = IntField()
	dietAddedOn = DateTimeField()
	recoverdOn = DateTimeField()
	status = IntField()

class StudentDetails(Document):
	rollNumber  = StringField()
	className = StringField()
	firstName = StringField()
	lastName = StringField()
	studentRefLink = StringField()
	height = IntField()
	weight = IntField()
	hemoglobin = IntField()
	age = StringField()
	month = StringField()
	bmiValue = IntField()
	createdOn = DateTimeField()
	attendanceStatus = IntField(default=2)
	attendenceDate = DateTimeField()
	status = IntField()


class StudentBmi(Document):
	studentName = StringField()
	className = StringField()
	rollNumber = StringField()
	height = IntField()
	weight = IntField()
	hemoglobin = IntField()
	age = StringField()
	month = StringField()
	bmiValue = IntField()
	studentRefLink = StringField()
	studentId = ReferenceField('StudentDetails')
	createdOn = DateTimeField()
	specialFoodItem = StringField()
	specialFoodQuantity = StringField()
	specialDietStatus = IntField()
	givenOn = DateTimeField()
	status = IntField()


